name: Build and deploy Node.js app to Azure Web App - mysafeshop-api
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        working-directory: backend
        run: npm install
      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate
      - name: Build NestJS
        working-directory: backend
        run: npm run build
      - name: Copy production files
        working-directory: backend
        run: |
          mkdir -p release
          cp -r dist release/
          cp package.json release/
          cp package-lock.json release/
          printf '[config]\nSCM_DO_BUILD_DURING_DEPLOYMENT=false\n' > release/.deployment
      - name: Install production dependencies
        working-directory: backend/release
        run: npm install --omit=dev
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/release
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: mysafeshop-api
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_250B9D21084743C29565480EC2E45656 }}
